### ISSUE TITLE
Could ipfs-log be helpful here ? or OrbitDB

### ISSUE THREAD

**Issue by lazyweirdo** [ipfs/public-gateway-checker#77] opened 2019-12-12 20:32 UTC
I was thinking about an easier way to add gateways. maybe through a web form ...
PRs are fine, but they put a little bit of friction to the process ... are they the only way, because there is something i am missing ?
Any thoughts on this ?

links
https://github.com/orbitdb/ipfs-log
https://github.com/orbitdb/orbit-db

**Comment by lazyweirdo** [comment] 2019-12-15 21:10
This is related to #61

**Comment by jamiew** [comment] 2019-12-18 16:01
Gonna close as duplicate of #61 since your suggestion sounds similar to that one -- a dynamic list of gateways.

That arguably should be a separate project from this. I know people explicitly reference the static `gateways.json` file in this repo so there's value in keeping in that

**Closed** 2019-12-18 16:01 UTC
